# This is a basic workflow to help you get started with Actions

name: Create Repo from issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: opened
# Hard-coded here, but representing the Topic to set for the created repo
env:
  mytopic: "tower-a"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
  issueop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Capture the issue that triggered the workflow into an environment variable
    env:
      GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}

    steps:
      - name: Dump GitHub context        
        run: echo "$GITHUB_ISSUE"
        
      - name: Create Repo
        run: |
          X=$(echo "$GITHUB_ISSUE" | jq .body)
          echo $X
          repo=${X:22:-1}
          echo $repo
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/orgs/${{ github.repository_owner }}/repos -d "{\"name\":\"$repo\"}"
          curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/repos/${{ github.repository_owner }}/$repo/topics -d "{\"names\":[\"${{ env.mytower }}\"]}"

