# This is a basic workflow to help you get started with Actions

name: Create Repo from issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: opened
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  myname: "test-repo"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
  issueop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context        
        run: echo "$GITHUB_ISSUE"
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          X=$(echo "$GITHUB_ISSUE" | jq .body)
          echo $X
          repo=${X:21:-0}
          echo $repo
#         curl -X POST "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/orgs/${{ github.repository_owner }}/repos -d '{"name":"${{ env.myname }}"}'
