# This is a basic workflow to help you get started with Actions

name: Create Repo from issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: opened
# Hard-coded here, but representing the Topic to set for the created repo
env:
  mytopic: "originations"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
  issueop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Capture the issue that triggered the workflow into an environment variable
    env:
      GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}

    steps:
      - name: Dump GitHub context        
        run: echo "$GITHUB_ISSUE"
        
      - name: Get New Repo Name
        id: getname
        run: |
          X=$(echo "$GITHUB_ISSUE" | jq .body)
          echo $X
          repo=${X:22:-1}
          echo $repo
          echo "::set-output name=reponame::$repo"
        
      - name: Create Repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/orgs/${{ github.repository_owner }}/repos -d "{\"name\":\"${{ steps.getname.outputs.reponame }}\"}"
          
      - name: Set Topic
        run: |
          curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.getname.outputs.reponame }}/topics -d "{\"names\":[\"${{ env.mytopic }}\"]}"

      - name: Close Issue
        run: |
          issuenum=$(echo "$GITHUB_ISSUE" | jq .number)
          echo The issue number to close is $issuenum
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: bearer ${{ secrets.My_PAT }}" https://api.github.com/repos/${{ github.repository }}/issues/"$issuenum" -d '{"state":"closed"}'
